Repository Leets-Official/X-BE, pull requests merged in 2024-11, with the labels that each got.

#17 [feat] #17 유저 프로필 수정 조회
  src/main/java/com/leets/X/domain/user/controller/ResponseMessage.java
  src/main/java/com/leets/X/domain/user/controller/UserController.java
  src/main/java/com/leets/X/domain/user/domain/User.java
  src/main/java/com/leets/X/domain/user/dto/request/UserUpdateRequest.java
  src/main/java/com/leets/X/domain/user/dto/response/UserProfileResponse.java
  src/main/java/com/leets/X/domain/user/service/UserService.java
Labels: feat

#18 [Feat] #18 피드 CRUD 기능 구현
  src/main/java/com/leets/X/domain/comment/domain/Comment.java
  src/main/java/com/leets/X/domain/image/domain/Image.java
  src/main/java/com/leets/X/domain/like/domain/Like.java
  src/main/java/com/leets/X/domain/like/repository/LikeRepository.java
  src/main/java/com/leets/X/domain/post/controller/PostController.java
  src/main/java/com/leets/X/domain/post/controller/ResponseMessage.java
  src/main/java/com/leets/X/domain/post/domain/Post.java
  src/main/java/com/leets/X/domain/post/domain/enums/IsDeleted.java
  src/main/java/com/leets/X/domain/post/dto/request/PostRequestDTO.java
  src/main/java/com/leets/X/domain/post/dto/response/CommentResponseDto.java
  src/main/java/com/leets/X/domain/post/dto/response/ImageResponseDto.java
  src/main/java/com/leets/X/domain/post/dto/response/PostResponseDto.java
  src/main/java/com/leets/X/domain/post/dto/response/PostUserResponse.java
  src/main/java/com/leets/X/domain/post/exception/AlreadyLikedException.java
  src/main/java/com/leets/X/domain/post/exception/ErrorMessage.java
  src/main/java/com/leets/X/domain/post/exception/NotLikedException.java
  src/main/java/com/leets/X/domain/post/exception/PostNotFoundException.java
  src/main/java/com/leets/X/domain/post/exception/UnauthorizedPostDeletionException.java
  src/main/java/com/leets/X/domain/post/repository/PostRepository.java
  src/main/java/com/leets/X/domain/post/service/PostService.java
  src/main/java/com/leets/X/domain/user/domain/User.java
Labels: feat

#21 [Feat] #21 팔로우 도메인 개발
  src/main/java/com/leets/X/domain/follow/controller/FollowController.java
  src/main/java/com/leets/X/domain/follow/controller/ResponseMessage.java
  src/main/java/com/leets/X/domain/follow/domain/Follow.java
  src/main/java/com/leets/X/domain/follow/dto/response/FollowResponse.java
  src/main/java/com/leets/X/domain/follow/exception/AlreadyFollowException.java
  src/main/java/com/leets/X/domain/follow/exception/ErrorMessage.java
  src/main/java/com/leets/X/domain/follow/exception/FollowNotFoundException.java
  src/main/java/com/leets/X/domain/follow/exception/InvalidFollowException.java
  src/main/java/com/leets/X/domain/follow/exception/InvalidUnfollowException.java
  src/main/java/com/leets/X/domain/follow/repository/FollowRepository.java
  src/main/java/com/leets/X/domain/follow/service/FollowService.java
  src/main/java/com/leets/X/domain/user/domain/User.java
  src/main/java/com/leets/X/domain/user/service/UserService.java
  src/main/java/com/leets/X/global/config/SecurityConfig.java
Labels: feat

#19 [Feat] #19 채팅 비지니스 로직 구현
  src/main/java/com/leets/X/domain/chat/controller/ChatRoomController.java
  src/main/java/com/leets/X/domain/chat/controller/ChattingController.java
  src/main/java/com/leets/X/domain/chat/controller/PublishMessageController.java
  src/main/java/com/leets/X/domain/chat/controller/ResponseMessage.java
  src/main/java/com/leets/X/domain/chat/dto/PublishMessage.java
  src/main/java/com/leets/X/domain/chat/dto/request/ChatRoomCheckRequstDto.java
  src/main/java/com/leets/X/domain/chat/dto/request/FindChatRoomRequestDto.java
  src/main/java/com/leets/X/domain/chat/dto/request/GetChatRoomRequestDto.java
  src/main/java/com/leets/X/domain/chat/dto/request/MessageDto.java
  src/main/java/com/leets/X/domain/chat/dto/response/ChatMessageResponseDto.java
  src/main/java/com/leets/X/domain/chat/dto/response/ChatRoomResponseDto.java
  src/main/java/com/leets/X/domain/chat/dto/response/ChattingDto.java
  src/main/java/com/leets/X/domain/chat/dto/response/ChattingListResponseDto.java
  src/main/java/com/leets/X/domain/chat/dto/response/LatestMessageDto.java
  src/main/java/com/leets/X/domain/chat/entity/ChatMessage.java
  src/main/java/com/leets/X/domain/chat/entity/ChatRoom.java
  src/main/java/com/leets/X/domain/chat/exception/ErrorMessage.java
  src/main/java/com/leets/X/domain/chat/exception/NotFoundChatRoomException.java
  src/main/java/com/leets/X/domain/chat/redis/RedisListener.java
  src/main/java/com/leets/X/domain/chat/redis/RedisPublisher.java
  src/main/java/com/leets/X/domain/chat/redis/RedisSubscriber.java
  src/main/java/com/leets/X/domain/chat/repository/ChatMessageRepository.java
  src/main/java/com/leets/X/domain/chat/repository/ChatRoomRepository.java
  src/main/java/com/leets/X/domain/chat/service/ChatRoomService.java
  src/main/java/com/leets/X/domain/chat/service/ChattingService.java
  src/main/java/com/leets/X/domain/chat/service/PublishMessageService.java
  src/main/java/com/leets/X/domain/user/exception/ErrorMessage.java
  src/main/java/com/leets/X/global/config/MongoDBConfig.java
  src/main/java/com/leets/X/global/config/RedisConfig.java
  src/main/java/com/leets/X/global/config/SecurityConfig.java
  src/main/resources/application-local.yml
  src/main/resources/application-prod.yml
Labels: feat

#29 Feat/#22/reply 기능 개발
  src/main/java/com/leets/X/domain/post/controller/PostController.java
  src/main/java/com/leets/X/domain/post/controller/ResponseMessage.java
  src/main/java/com/leets/X/domain/post/domain/Post.java
  src/main/java/com/leets/X/domain/post/dto/response/CommentResponseDto.java
  src/main/java/com/leets/X/domain/post/dto/response/ImageResponseDto.java
  src/main/java/com/leets/X/domain/post/dto/response/ParentPostResponseDto.java
  src/main/java/com/leets/X/domain/post/dto/response/PostResponseDto.java
  src/main/java/com/leets/X/domain/post/dto/response/PostUserResponse.java
  src/main/java/com/leets/X/domain/post/repository/PostRepository.java
  src/main/java/com/leets/X/domain/post/service/PostService.java
  src/main/java/com/leets/X/global/auth/jwt/JwtFilter.java
  src/main/java/com/leets/X/global/config/RedisConfig.java
  src/main/resources/application-local.yml
Labels: feat, refactor, fix

#26 Feat #26 팔로워수 반환 및 프로필 조회시 팔로우 여부 반환
  src/main/java/com/leets/X/domain/follow/service/FollowService.java
  src/main/java/com/leets/X/domain/user/controller/UserController.java
  src/main/java/com/leets/X/domain/user/domain/User.java
  src/main/java/com/leets/X/domain/user/domain/enums/LoginStatus.java
  src/main/java/com/leets/X/domain/user/dto/response/UserProfileResponse.java
  src/main/java/com/leets/X/domain/user/dto/response/UserSocialLoginResponse.java
  src/main/java/com/leets/X/domain/user/service/UserService.java
Labels: feat, refactor

#25 [feat] #25 이미지 업로드 및 게시글과 함께 저장
  build.gradle
  src/main/java/com/leets/X/domain/image/domain/Image.java
  src/main/java/com/leets/X/domain/image/dto/request/ImageDto.java
  src/main/java/com/leets/X/domain/image/dto/response/ImageResponse.java
  src/main/java/com/leets/X/domain/image/exception/ErrorMessage.java
  src/main/java/com/leets/X/domain/image/exception/S3UploadException.java
  src/main/java/com/leets/X/domain/image/repository/ImageRepository.java
  src/main/java/com/leets/X/domain/image/service/ImageService.java
  src/main/java/com/leets/X/domain/image/service/ImageUploadService.java
  src/main/java/com/leets/X/domain/post/controller/PostController.java
  src/main/java/com/leets/X/domain/post/domain/Post.java
  src/main/java/com/leets/X/domain/post/dto/response/ParentPostResponseDto.java
  src/main/java/com/leets/X/domain/post/dto/response/PostResponseDto.java
  src/main/java/com/leets/X/domain/post/service/PostService.java
  src/main/java/com/leets/X/global/config/S3/S3Config.java
  src/main/java/com/leets/X/global/config/swagger/OctetStreamReadMsgConverter.java
  src/main/java/com/leets/X/global/config/swagger/SwaggerConfig.java
  src/main/resources/application.yml
Labels: feat

#31 [feat] #31 repost 기능 구현 및 코드 통합
  src/main/java/com/leets/X/domain/post/controller/PostController.java
  src/main/java/com/leets/X/domain/post/controller/ResponseMessage.java
  src/main/java/com/leets/X/domain/post/domain/Repost.java
  src/main/java/com/leets/X/domain/post/domain/enums/Type.java
  src/main/java/com/leets/X/domain/post/dto/mapper/PostMapper.java
  src/main/java/com/leets/X/domain/post/dto/response/ImageResponseDto.java
  src/main/java/com/leets/X/domain/post/dto/response/ParentPostResponseDto.java
  src/main/java/com/leets/X/domain/post/dto/response/PostResponseDto.java
  src/main/java/com/leets/X/domain/post/exception/AlreadyRepostException.java
  src/main/java/com/leets/X/domain/post/exception/ErrorMessage.java
  src/main/java/com/leets/X/domain/post/repository/RepostRepository.java
  src/main/java/com/leets/X/domain/post/service/PostService.java
  src/main/java/com/leets/X/domain/post/service/RepostService.java
  src/main/java/com/leets/X/domain/user/domain/User.java
Labels: feat, refactor

#33 [refactor] #33 수정 사항 추가
  src/main/java/com/leets/X/domain/image/domain/Image.java
  src/main/java/com/leets/X/domain/image/service/ImageService.java
  src/main/java/com/leets/X/domain/image/service/ImageUploadService.java
  src/main/java/com/leets/X/domain/post/domain/Post.java
  src/main/java/com/leets/X/domain/post/dto/mapper/PostMapper.java
  src/main/java/com/leets/X/domain/post/dto/response/ParentPostResponseDto.java
  src/main/java/com/leets/X/domain/post/dto/response/PostResponseDto.java
  src/main/java/com/leets/X/domain/post/dto/response/PostUserResponse.java
  src/main/java/com/leets/X/domain/post/service/PostService.java
  src/main/java/com/leets/X/domain/post/service/RepostService.java
  src/main/java/com/leets/X/domain/user/controller/UserController.java
  src/main/java/com/leets/X/domain/user/domain/User.java
  src/main/java/com/leets/X/domain/user/dto/response/UserProfileResponse.java
  src/main/java/com/leets/X/domain/user/service/UserService.java
  src/main/resources/application.yml
Labels: feat, refactor

#35 Docs/#34/readme 파일 내용 수정
  README.md
  img.png
Labels: docs
